apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: fast-api
  namespace: argocd
spec: 
  destination: 
    namespace: fast-api
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd-deployment
    repoURL: "https://github.com/Mbaoma/fastAPI.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true